#!/usr/bin/env python3
"""Generate and statically validate the conveyor workcell selective-reference layer.

Run inside the Isaac Lab environment because reading the source crate requires USD:

    python tools/build_conveyor_workcell_lite.py
    python tools/build_conveyor_workcell_lite.py --check

The output intentionally stays ASCII despite the ``.usd`` suffix.  It references only whitelisted
top-level prims from the versioned v61 visual-only asset, so pruned references do not enter the
composed stage and regeneration does not duplicate remote geometry into the Git repository.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = (
    REPO_ROOT
    / "tasks/g1_tasks/g1_29dof_sonic_conveyor/scene_assets"
)
MANIFEST_PATH = ASSET_DIR / "conveyor_workcell_lite.manifest.json"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail when the checked-in layer or its audit contract is stale.",
    )
    return parser.parse_args()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _quoted(identifier: str) -> str:
    return json.dumps(identifier, ensure_ascii=False)


def _render_layer(source_name: str, kept_root_names: list[str]) -> str:
    lines = [
        "#usda 1.0",
        "(",
        '    defaultPrim = "Root"',
        "    metersPerUnit = 1",
        '    upAxis = "Z"',
        ")",
        "",
        "# Generated by tools/build_conveyor_workcell_lite.py. Do not edit by hand.",
        "# Reference only required source subtrees; omitted warehouse props never enter composition.",
        'def Xform "Root"',
        "{",
    ]
    for name in kept_root_names:
        lines.extend(
            [
                f"    def Xform {_quoted(name)} (",
                f"        prepend references = @./{source_name}@</Root/{name}>",
                "    )",
                "    {",
                "    }",
                "",
            ]
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def _is_kept(name: str, manifest: dict) -> bool:
    return name in manifest["keep_root_exact"] or any(
        name.startswith(prefix) for prefix in manifest["keep_root_prefixes"]
    )


def _prim_is_effectively_active(stage, path: str) -> bool:
    prim = stage.GetPrimAtPath(path)
    return bool(prim) and prim.IsActive()


def main() -> int:
    args = _parse_args()
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    source_path = ASSET_DIR / manifest["source_asset"]
    output_path = ASSET_DIR / manifest["output_asset"]

    actual_sha = _sha256(source_path)
    if actual_sha != manifest["source_asset_sha256"]:
        print(
            "[workcell_lite] source SHA256 changed; audit the new v61 composition and update the manifest:\n"
            f"  expected={manifest['source_asset_sha256']}\n  actual={actual_sha}",
            file=sys.stderr,
        )
        return 2

    # USD/Kit imports must happen after AppLauncher creates the runtime.  Keeping them local also
    # lets ordinary Python unit tests inspect the manifest and generated ASCII layer.
    from isaaclab.app import AppLauncher

    launcher = AppLauncher(headless=True, device="cpu")
    simulation_app = launcher.app
    try:
        from pxr import Usd

        source_stage = Usd.Stage.Open(str(source_path))
        if not source_stage:
            print(f"[workcell_lite] cannot open source: {source_path}", file=sys.stderr)
            return 2
        source_root = source_stage.GetDefaultPrim()
        source_children = list(source_root.GetChildren())
        if len(source_children) != manifest["source_root_child_count"]:
            print(
                "[workcell_lite] source root inventory changed; re-audit keep rules before regenerating: "
                f"expected={manifest['source_root_child_count']} actual={len(source_children)}",
                file=sys.stderr,
            )
            return 2

        source_names = {prim.GetName() for prim in source_children}
        missing_kept = sorted(set(manifest["keep_root_exact"]) - source_names)
        if missing_kept:
            print(f"[workcell_lite] kept roots missing from source: {missing_kept}", file=sys.stderr)
            return 2

        kept_names = sorted(
            prim.GetName() for prim in source_children if _is_kept(prim.GetName(), manifest)
        )
        generated = _render_layer(source_path.name, kept_names)

        if args.check:
            if not output_path.is_file() or output_path.read_text(encoding="utf-8") != generated:
                print(
                    "[workcell_lite] checked-in layer is stale; run without --check to regenerate",
                    file=sys.stderr,
                )
                return 1
        else:
            output_path.write_text(generated, encoding="utf-8")
            print(f"[workcell_lite] wrote {output_path}")

        lite_stage = Usd.Stage.Open(str(output_path))
        if not lite_stage:
            print(f"[workcell_lite] cannot open generated layer: {output_path}", file=sys.stderr)
            return 2

        bad_active = [
            path
            for path in manifest["required_active_prims"]
            if not _prim_is_effectively_active(lite_stage, path)
        ]
        bad_inactive = [
            path
            for path in manifest["required_inactive_prims"]
            if _prim_is_effectively_active(lite_stage, path)
        ]
        if bad_active or bad_inactive:
            print(
                f"[workcell_lite] composition contract failed: inactive_kept={bad_active}, "
                f"active_pruned={bad_inactive}",
                file=sys.stderr,
            )
            return 2

        forbidden_types = set(manifest["forbidden_active_type_names"])
        forbidden_type_prims = [
            f"{prim.GetPath()}:{prim.GetTypeName()}"
            for prim in lite_stage.Traverse()
            if prim.IsActive() and prim.GetTypeName() in forbidden_types
        ]
        if forbidden_type_prims:
            print(
                f"[workcell_lite] forbidden runtime prim types remain: {forbidden_type_prims}",
                file=sys.stderr,
            )
            return 2

        source_active = sum(1 for prim in source_stage.Traverse() if prim.IsActive())
        lite_active = sum(1 for prim in lite_stage.Traverse() if prim.IsActive())
        source_layers = len(source_stage.GetUsedLayers())
        lite_layers = len(lite_stage.GetUsedLayers())
        limits = manifest["audit_limits"]
        failures = []
        if lite_active > limits["max_lite_active_prims"]:
            failures.append(f"lite active prims {lite_active} > {limits['max_lite_active_prims']}")
        if lite_layers > limits["max_lite_used_layers"]:
            failures.append(f"lite used layers {lite_layers} > {limits['max_lite_used_layers']}")
        if source_active - lite_active < limits["min_active_prim_reduction"]:
            failures.append(
                f"active prim reduction {source_active - lite_active} < "
                f"{limits['min_active_prim_reduction']}"
            )
        if source_layers - lite_layers < limits["min_used_layer_reduction"]:
            failures.append(
                f"used layer reduction {source_layers - lite_layers} < "
                f"{limits['min_used_layer_reduction']}"
            )
        if failures:
            print("[workcell_lite] audit limits failed: " + "; ".join(failures), file=sys.stderr)
            return 2

        remote_prefix = manifest["remote_dependency_prefix"]
        remote_layers = sorted(
            layer.identifier
            for layer in lite_stage.GetUsedLayers()
            if layer.identifier.startswith(remote_prefix)
        )
        if len(remote_layers) != manifest["expected_lite_remote_layers"]:
            print(
                "[workcell_lite] retained remote dependency count changed: "
                f"expected={manifest['expected_lite_remote_layers']} actual={len(remote_layers)}",
                file=sys.stderr,
            )
            return 2
        print(
            "[workcell_lite] PASS "
            f"root kept={len(kept_names)} omitted={len(source_children) - len(kept_names)} "
            f"| active prims {source_active}->{lite_active} "
            f"| used layers {source_layers}->{lite_layers} | retained remote layers={len(remote_layers)}",
            flush=True,
        )
        for identifier in remote_layers:
            print(f"[workcell_lite] remote: {identifier}", flush=True)
        return 0
    finally:
        simulation_app.close()


if __name__ == "__main__":
    raise SystemExit(main())
